[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173  # Default port for Vite
  publish = "dist"

[context.preview]
  branch = "preview"
  publish = "dist"
  command = "npm run build"

[context.development.environment]
  VITE_LOG_LEVEL = "info"
